### ISSUE TITLE
Deprecated or not?

### ISSUE THREAD

**Issue by chludwig-haufe** [nebula-plugins/gradle-aggregate-javadocs-plugin#11]
The commits 509a3d551642b07831c12c7d71f19f42b351f777 and 5888f7c402f08d5f7c587f71e405d58c327eca6a added a "deprecated" support badge to the README.md. However, I cannot find any deprecation notice and the [Nebula Plugin Overview](https://nebula-plugins.github.io/documentation/plugin_overview.html) still lists gradle-aggregate-javadocs-plugin under _Miscellaneous_ rather than _Deprecated_.

Could you please clarify this plugin's support status? In case it is in fact deprecated, do you have suggestions for alternatives? Thanks!

**Comment by DanielThomas** [comment]
Hi @chludwig-haufe - I've updated that badge to read 'inactive', because that better reflects what we're trying to communicate with those badges. We're not using that plugin internally and it's not under active development. 

We'll keep these plugins working on later Gradle versions and accept pull requests, until the maintenance overhead gets too much and then we'll deprecate them completely. If the plugin works, there's no reason not to keep using it.
